### ISSUE TITLE
Lab 9 move errors

### ISSUE THREAD

**Issue by ghost** [nrwl/nx-workshop#1]
Got an error in Lab 9 when attempting to move the library. Is this a bug or a known issue? 

It worked when Jason did it in the Pluralsight Course video in Part 4.

>`nx generate @nrwl/workspace:move --projectName=api-util-interface util-interface`
**ENOTEMPTY: directory not empty, rmdir 'C:\Code\vsCode\nx-workshop\bg-hoard\libs\api\util-interface\src'**

This error messed up my project, it deleted the files but didn't create the new ones that --dry-run indicated it would.  **I'm so glad I checked in before attempting this.**

nx --version
9.5.1

ng --version
Angular: 9.1.11

Thank you!

Karl

**Comment by rarmatei** [comment]
I updated the workshop recently - can you please try again? I'm closing this for now.
